version: "3.8"
x-common-variables: &common-variables
  MYSQL_DATABASE: todoapp
  MYSQL_USER: admin
  MYSQL_PASSWORD: admin

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "9906:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost
      
  api:
    build: ./api 
    container_name: api
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

  myblog:
    build: ./client
    container_name: client
    ports:
      - '5173:5173'
    volumes:
    - ./client:/app
    - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true